#!/bin/sh
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/1.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/10.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/12.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/14.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/16.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/18.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/2.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/20.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/23.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/25.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/27.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/29.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/3.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/31.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/33.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/35.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/37.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/39.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/4.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/42.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/44.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/46.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/48.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/5.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/50.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/52.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/6.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/7.csv
wget https://raw.githubusercontent.com/taiwaich/olympics/main/summer-games/8.csv